# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np

In [3]:
np.empty((3,3,3))

array([[[1.12423735e-311, 1.12423199e-311, 1.37961302e-306],
        [6.23053614e-307, 6.23053954e-307, 9.34609790e-307],
        [8.45593934e-307, 9.34600963e-307, 1.86921143e-306]],

       [[6.23061763e-307, 1.78021527e-306, 6.23055651e-307],
        [1.11261434e-306, 9.34609790e-307, 1.42417629e-306],
        [8.45593934e-307, 6.89805151e-307, 8.45596650e-307]],

       [[1.78019082e-306, 8.34451504e-308, 1.78022342e-306],
        [8.06635958e-308, 1.42410974e-306, 3.20558931e-317],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]]])

In [4]:
Z = np.random.uniform((3,3,3))
print (Z)

[1.82183937 2.0385945  1.6041762 ]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [5]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [7]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.46913737 0.57998475 0.23367164 0.349812   0.6964404 ]
 [0.49214308 0.42059678 0.17897125 0.08902082 0.58993317]
 [0.74587193 0.16816572 0.13473855 0.58809731 0.24537156]
 [0.42513642 0.55756754 0.46982461 0.50569318 0.50875567]
 [0.18738199 0.04132595 0.         1.         0.63939261]]


# 5.  How to find common values between two arrays?

In [8]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [1 , 10, 2, 40 ,3]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [1, 10, 2, 40, 3]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)


Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [11]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)


First array:
[0 1 0 1 1 1]
Second array:
[0 0 1 1 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [12]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = -0
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.86001354 0.83510522 0.88414281 0.95818159 0.75036184 0.45418404
 0.27329279 0.97585379 0.18685519 0.09272804]
Maximum value replaced by -1:
[0.86001354 0.83510522 0.88414281 0.95818159 0.75036184 0.45418404
 0.27329279 0.         0.18685519 0.09272804]


# 9. How to print all the values of an array?

In [16]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.zeros((4, 4))
print(x)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [18]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.8405304  0.69000941 0.72289169 0.70589348 0.98275361]
 [0.79697859 0.81586837 0.59773755 0.4400716  0.86656005]
 [0.41420994 0.15130931 0.72160289 0.69071886 0.54547071]
 [0.289454   0.4899149  0.47269111 0.5546625  0.02219345]
 [0.3591078  0.08815541 0.92738132 0.79970971 0.59344511]]

Subtract the mean of each row of the said matrix:

[[ 0.05211469 -0.09840631 -0.06552403 -0.08252223  0.19433789]
 [ 0.09353536  0.11242514 -0.10570568 -0.26337164  0.16311682]
 [-0.09045241 -0.35335303  0.21694055  0.18605652  0.04080837]
 [-0.07632919  0.12413171  0.10690792  0.18887931 -0.34358974]
 [-0.19445207 -0.46540446  0.37382145  0.24614984  0.03988524]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [34]:
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])
print(vector_row)
addone = vector_row + 1
addone

[1 2 3]


array([2, 3, 4])

# 12.How to get the diagonal of a dot product?

In [27]:
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)

np.diag(np.dot(np.dot(a, b), a.T))


array([  60,  672, 1932, 3840, 6396])

# 13.How to find the most frequent value in an array?

In [20]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 7 3 5 8 3 9 6 3 7 6 0 3 7 3 4 9 4 0 3 8 1 6 8 9 9 9 8 7 2 0 3 9 8 2 8 3
 2 3 6]
Most frequent value in the above array:
3


# 14.How to get the n largest values of an array

In [21]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])


Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [24]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Chitra','Navya','Sri','Siri'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])
print(result[3])

(1, 'Chitra', 12.2)
(2, 'Navya', 15.)
(3, 'Sri', 20.)
(4, 'Siri', 40.)
